stolostron/observatorium

Makefile

https://github.com/open-cluster-management/backlog/issues/10627
Signed-off-by: Song Song Li <ssli@redhat.com>

fix build cmd

---

Dockerfile

https://github.com/open-cluster-management/backlog/issues/11665
Signed-off-by: Song Song Li <ssli@redhat.com>

add microdnf update

---

.gitignore
vendor/github.com/observatorium/up/LICENSE
vendor/github.com/observatorium/up/cmd/up/main.go
vendor/github.com/observatorium/up/pkg/auth/doc.go
vendor/github.com/observatorium/up/pkg/auth/roundtripper.go
vendor/github.com/observatorium/up/pkg/auth/token.go
vendor/github.com/observatorium/up/pkg/instr/doc.go
vendor/github.com/observatorium/up/pkg/instr/metrics.go
vendor/github.com/observatorium/up/pkg/logs/doc.go
vendor/github.com/observatorium/up/pkg/logs/read.go
vendor/github.com/observatorium/up/pkg/logs/types.go
vendor/github.com/observatorium/up/pkg/logs/write.go
vendor/github.com/observatorium/up/pkg/metrics/doc.go
vendor/github.com/observatorium/up/pkg/metrics/query.go
vendor/github.com/observatorium/up/pkg/metrics/read.go
vendor/github.com/observatorium/up/pkg/metrics/write.go
vendor/github.com/observatorium/up/pkg/options/doc.go
vendor/github.com/observatorium/up/pkg/options/options.go
vendor/github.com/observatorium/up/pkg/transport/body.go
vendor/github.com/observatorium/up/pkg/transport/doc.go
vendor/github.com/observatorium/up/pkg/transport/tls.go
vendor/github.com/observatorium/up/pkg/transport/transport.go

https://github.com/open-cluster-management/backlog/issues/13135
to include observatorium/up in vendor folder so that it can pass the go vendor check in ds build.
Signed-off-by: Marco <llan@redhat.com>

update .gitignore, to only ignore the /observatorium

---

go.mod
go.sum
vendor/github.com/gogo/protobuf/proto/text_parser.go
vendor/github.com/gogo/protobuf/types/any.pb.go
vendor/github.com/gogo/protobuf/types/api.pb.go
vendor/github.com/gogo/protobuf/types/duration.pb.go
vendor/github.com/gogo/protobuf/types/empty.pb.go
vendor/github.com/gogo/protobuf/types/field_mask.pb.go
vendor/github.com/gogo/protobuf/types/source_context.pb.go
vendor/github.com/gogo/protobuf/types/struct.pb.go
vendor/github.com/gogo/protobuf/types/timestamp.pb.go
vendor/github.com/gogo/protobuf/types/type.pb.go
vendor/github.com/gogo/protobuf/types/wrappers.pb.go
vendor/modules.txt

https://github.com/open-cluster-management/backlog/issues/15967
Signed-off-by: Marco <llan@redhat.com>

upgrade vulnerable lib

---

jsonnet/lib/observatorium-api.libsonnet

https://github.com/open-cluster-management/backlog/issues/18022

update to use latest jsonnet, also add tenant-header support

---

internal/api/metrics/v1/http.go
internal/proxy/proxy.go

https://github.com/open-cluster-management/observatorium-operator/pull/55

update write path to handle write endpoint which is not thanos receive

---

internal/proxy/proxy.go

https://github.com/open-cluster-management/backlog/issues/18022

handle the path for different write backend

---

jsonnet/lib/observatorium-api.libsonnet
test/mock/provider.go
test/tls/generate.go
tools.go

ref: open-cluster-management/backlog#18192
Signed-off-by: morvencao <lcao@redhat.com>

add imagepullpolicy support.

---

go.mod
go.sum
internal/api/metrics/v1/http.go
internal/remotewrite/proxy.go
jsonnet/lib/observatorium-api.libsonnet
main.go

https://github.com/stolostron/backlog/issues/19996

support remote write endpoints

---

jsonnet/lib/observatorium-api.libsonnet

replace hard coded mount path from config

---

internal/remotewrite/proxy.go

https://github.com/stolostron/backlog/issues/20667

customize http options for case without http client config

---

OWNERS

Trigger build to address package vulnerabilities
Signed-off-by: Subbarao Meduri <smeduri@redhat.com>

updated owners, reviewers

---

README.md

Signed-off-by: Subbarao Meduri <smeduri@redhat.com>

trigger build of all images for openssl fix

---

README.md

Signed-off-by: marcolan018 <llan@redhat.com>

rebuild image

---

README.md
test/mock/provider.go
test/tls/generate.go
tools.go

Related issue: https://github.com/stolostron/backlog/issues/22158
Signed-off-by: dislbenn <dbennett@redhat.com>

[release-2.3] Triggering image rebuild

---

Dockerfile
go.mod
go.sum

Related issue: https://github.com/stolostron/backlog/issues/24211
Signed-off-by: dislbenn <dbennett@redhat.com>

[release-2.6] Updated go to 1.18

---

sonar-project.properties

Related issue: https://github.com/stolostron/backlog/issues/24274
Signed-off-by: dislbenn <dbennett@redhat.com>

[release-2.4] Added sonar project properties file to repo

---

README.md

Signed-off-by: Subbarao Meduri <smeduri@redhat.com>

trigger rebuild to pick up base OS CVE fixes

---

README.md

Signed-off-by: Subbarao Meduri <smeduri@redhat.com>

Rebuild with new base image

---

Dockerfile
Makefile

**Changes:**  Changes the CGO_ENABLED flag to 1 / Changes TLS Version to 1.2.

[release-2.7] Change CGO_ENABLED to 1 / Changed TLS Version to 1.2

---

Dockerfile
Makefile

**Changes:**  Changes the CGO_ENABLED flag to 1 / Changes TLS Version to 1.2.

[main] Change CGO_ENABLED to 1 / Changed TLS Version to 1.2

---

Dockerfile
Makefile

**Changes:**  Changes the CGO_ENABLED flag to 1 / Changes TLS Version to 1.2.

[release-2.8] Change CGO_ENABLED to 1 / Changed TLS Version to 1.2

---

internal/api/metrics/v1/http.go
internal/remotewrite/proxy.go

Cherry pick of https://github.com/stolostron/observatorium/pull/80

[ACM 11801]: Prefer stdlib ReverseProxy implementation when no additional endpoints are configured

---

go.mod
go.sum

Bump go x/net and x/crypto

---

.tekton/observatorium-acm-213-pull-request.yaml
.tekton/observatorium-acm-213-push.yaml

Konflux: make release-2.13 target release-2.13

---

.tekton/observatorium-acm-213-pull-request.yaml
.tekton/observatorium-acm-213-push.yaml

See individual commits for details

Konflux changes for release-2.13

---

.tekton/observatorium-acm-211-pull-request.yaml
.tekton/observatorium-acm-211-push.yaml
Containerfile.operator

See individual commits for details

Konflux changes for release-2.11
